# ~/.config/hypr/hypridle.conf

general {
    lock_cmd = pidof hyprlock || hyprlock       # Avoid launching multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # Lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # Turn display back on after resume
}

# 1. Dim screen backlight after 2.5 minutes
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# 2. Lock screen after 5 minutes
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 3. Turn off screen (DPMS) after 5.5 minutes
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 4. Suspend system after 30 minutes
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
