-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "WhiteSur-cursors")
hl.env("XCURSOR_SIZE", "27")

-- Settings
hl.config({
    decoration = {
        active_opacity = 0.93,
        blur = {
            contrast = 0.31,
            enabled = true,
            noise = 0.011,
            passes = 1,
            size = 3,
            xray = false,
        },
        fullscreen_opacity = 0.95,
        inactive_opacity = 0.93,
        rounding = 5,
        shadow = {
            enabled = false,
        },
    },
    dwindle = {
        force_split = 0,
        preserve_split = false,
    },
    general = {
        allow_tearing = true,
        col = {
            inactive_border = "0x7ff5bde6",
        },
        gaps_out = 10,
        layout = "dwindle",
    },
})
