-- Generated by nwg-displays on 2026-09-02 at 00:35:38. Do not edit manually.

hl.monitor({
    output = "DP-3",
    mode = "1920x1080@100.0",
    position = "0x0",
    scale = 1,
    bitdepth = 10,
    vrr = 0
})
